# Generated by Django 5.2 on 2025-04-26 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('type', models.CharField(choices=[('income', 'Income'), ('expense', 'Expense'), ('budget', 'Budget'), ('transaction', 'Transaction')], max_length=20)),
                ('built_in', models.BooleanField(default=False)),
            ],
        ),
    ]
